Repository Hello-PixelBeat/PixelBeat, pull requests merged in 2024-01, with the labels that each got.

#6 Feat: 영수증 페이지 구현 #5
  index.html
  package-lock.json
  package.json
  src/api/supabase/playlistTableAccessApis.ts
  src/api/supabase/profilesTableAccessApis.ts
  src/assets/images/barcode.png
  src/assets/images/billBackground.png
  src/assets/images/graphBackground.png
  src/assets/index.ts
  src/assets/svgs/CirclePlaySmall.svg
  src/assets/svgs/Clock.svg
  src/assets/svgs/NavHome.svg
  src/assets/svgs/NavMyMusic.svg
  src/assets/svgs/NavProfile.svg
  src/assets/svgs/NavSearch.svg
  src/components/bill/BillButtonListSection.tsx
  src/components/bill/BillChart.tsx
  src/components/bill/BillItem.tsx
  src/components/bill/billChartOption.ts
  src/components/common/ConfirmModal.tsx
  src/components/common/NavBar.tsx
  src/components/common/NavItem.tsx
  src/components/recommend/RecommendButton.tsx
  src/components/recommend/TrackItem.tsx
  src/components/recommend/TrackSelector.tsx
  src/components/svgComponents/SmallButton.tsx
  src/components/svgComponents/index.ts
  src/constants/billText.ts
  src/constants/buttonText.ts
  src/constants/confirmText.ts
  src/constants/navText.ts
  src/constants/spinnerText.ts
  src/hooks/useConfirm.ts
  src/index.css
  src/pages/Page-GuestBill.tsx
  src/pages/Page-RecommendEntry.tsx
  src/pages/Page-UserBill.tsx
  src/types/recommendTypes.ts
  src/utils/formatDate.ts
  src/utils/msToMinutesAndSeconds.ts
  src/utils/portal.ts
  src/utils/shareData.ts
  src/zustand/confirmStore.ts
  src/zustand/playNowStore.ts
  src/zustand/recommendStore.ts
Labels: 기능 추가, 스타일

#8 Feat: 현재 재생중인 음악확인 기능 구현 #7
  src/api/supabase/profilesTableAccessApis.ts
  src/assets/images/defaultAlbumImage.png
  src/assets/images/playerFullScreenButtonBackground.png
  src/assets/images/progressDot.png
  src/assets/svgs/ArrowDown.svg
  src/assets/svgs/CirclePause.svg
  src/assets/svgs/CirclePlay.svg
  src/assets/svgs/MoreIcon.svg
  src/assets/svgs/MusicList.svg
  src/assets/svgs/PlayerNextButton.svg
  src/assets/svgs/PlayerPauseButton.svg
  src/assets/svgs/PlayerPlayButton.svg
  src/assets/svgs/PlayerPrevButton.svg
  src/assets/svgs/SoundOff.svg
  src/assets/svgs/SoundOn.svg
  src/components/bill/BillItem.tsx
  src/components/common/Header.tsx
  src/components/musicPlayer/MusicPlayerBar.tsx
  src/components/musicPlayer/MusicPlayerControls.tsx
  src/components/musicPlayer/MusicPlayerFullScreen.tsx
  src/components/musicPlayer/MusicPlayerProgressBar.tsx
  src/components/musicPlayer/PlayerTrackInfo.tsx
  src/components/recommend/ArtistItem.tsx
  src/components/recommend/ArtistSelector.tsx
  src/components/recommend/RecommendButton.tsx
  src/components/recommend/TrackItem.tsx
  src/constants/playbackText.ts
  src/hooks/useModal.ts
  src/hooks/usePlayerControls.ts
  src/index.css
  src/pages/Page-GuestBill.tsx
  src/pages/Wrapper.tsx
  src/types/playerTypes.ts
  src/zustand/modalStore.ts
Labels: 기능 추가, 스타일

#11 Feat: 구글, 카카오 로그인 기능 구현 및 프로필 업로드 및 수정 페이지
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  package-lock.json
  package.json
  public/manifest.json
  public/pwabuilder-sw.js
  src/api/axios.ts
  src/api/supabase/authApis.ts
  src/api/supabase/imageStorageAccessApis.ts
  src/api/supabase/profilesTableAccessApis.ts
  src/assets/images/Profile.png
  src/assets/svgs/EmailIcon.svg
  src/assets/svgs/GoogleIcon.svg
  src/assets/svgs/ImageUploadIcon.svg
  src/assets/svgs/KakaoIcon.svg
  src/assets/svgs/VisitorIcon.svg
  src/components/bill/BillButtonListSection.tsx
  src/components/bill/BillItem.tsx
  src/components/musicPlayer/MusicPlayerBar.tsx
  src/components/musicPlayer/MusicPlayerFullScreen.tsx
  src/components/musicPlayer/MusicPlayerProgressBar.tsx
  src/components/profile/ImageUploadForm.tsx
  src/components/profile/ProfileForm.tsx
  src/components/profile/ProfileInputField.tsx
  src/components/recommend/ArtistSelector.tsx
  src/components/recommend/TrackSelector.tsx
  src/components/svgComponents/Spinner.tsx
  src/components/svgComponents/StandardButton.tsx
  src/components/svgComponents/index.ts
  src/constants/routes.ts
  src/hooks/usePlayerControls.ts
  src/hooks/useUpdateUserInfoMutation.ts
  src/hooks/useUserInfo.ts
  src/hooks/useUserSession.ts
  src/main.tsx
  src/pages/Page-Entry.tsx
  src/pages/Page-GuestBill.tsx
  src/pages/Page-Home.tsx
  src/pages/Page-ProfileEdit.tsx
  src/pages/Page-ProfileUpload.tsx
  src/pages/Page-SignupGreeting.tsx
  src/pages/PrivateRoute.tsx
  src/pages/PublicRoute.tsx
  src/pages/Router.tsx
  src/pages/Wrapper.tsx
  src/utils/getUserIdFromLocalStorage.ts
  src/utils/getUserIdFromSession.ts
  src/utils/loadTokenAndCheckExpiration.ts
  src/utils/navigateAfterSignInWithOAuth.ts
  src/zustand/playNowStore.ts
  src/zustand/userStore.ts
Labels: 기능 추가, 수정, 스타일

#14 Feat: email로 회원가입 및 로그인 기능 구현
  src/api/supabase/authApis.ts
  src/assets/svgs/ClosedEye.svg
  src/assets/svgs/Eye.svg
  src/components/SignIn/InputSection.tsx
  src/components/SignIn/SignInForm.tsx
  src/components/SignIn/SigninInputField.tsx
  src/components/signUp/SignUpForm.tsx
  src/components/signUp/SignupInputField.tsx
  src/components/signUp/ValidationErrorMessage.tsx
  src/pages/Page-Login.tsx
  src/pages/Page-Signup.tsx
Labels: 기능 추가, 수정

#18 REFACTOR: zustand persist
  src/api/supabase/profilesTableAccessApis.ts
  src/assets/svgs/ArrowDown.svg
  src/components/bill/BillBox_User.tsx
  src/components/common/Header.tsx
  src/components/common/NavItem.tsx
  src/components/home/PopularUserBill.tsx
  src/components/mymusic/MusicList.tsx
  src/components/mypage/MyProfileInfo.tsx
  src/components/profile/ProfileBillList.tsx
  src/components/profile/ProfileForm.tsx
  src/components/profile/ProfileInfo.tsx
  src/components/profile/ProfileLikeBillList.tsx
  src/components/profile/ProfileSmallBill.tsx
  src/components/search/RecentSearchList.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchResultPlaylist.tsx
  src/constants/buttonText.ts
  src/constants/confirmText.ts
  src/constants/navText.tsx
  src/constants/routes.ts
  src/main.tsx
  src/pages/Page-MyPage.tsx
  src/pages/Page-User.tsx
  src/zustand/searchStore.ts
Labels: 기능 추가, 수정

#22 Feat: 리액트 헬멧 적용하기
  index.html
  package-lock.json
  package.json
  public/icons/apple-touch-icon-114x114.png
  public/icons/apple-touch-icon-120x120.png
  public/icons/apple-touch-icon-144x144.png
  public/icons/apple-touch-icon-152x152.png
  public/icons/apple-touch-icon-57x57.png
  public/icons/apple-touch-icon-60x60.png
  public/icons/apple-touch-icon-72x72.png
  public/icons/apple-touch-icon-76x76.png
  public/icons/favicon-128.png
  public/icons/favicon-16x16.png
  public/icons/favicon-196x196.png
  public/icons/favicon-32x32.png
  public/icons/favicon-96x96.png
  public/icons/favicon.ico
  public/icons/mstile-144x144.png
  public/icons/mstile-150x150.png
  public/icons/mstile-310x150.png
  public/icons/mstile-310x310.png
  public/icons/mstile-70x70.png
  public/manifest.json
  src/components/bill/BillBox_User.tsx
  src/components/common/MainMetaTag.tsx
  src/components/common/MetaTag.tsx
  src/components/profile/ProfileBillList.tsx
  src/components/profile/ProfileLikeBillList.tsx
  src/main.tsx
  src/pages/Page-GuestBill.tsx
  src/pages/Page-User.tsx
  src/pages/Wrapper.tsx
Labels: 버그, 기능 추가, 수정

#23 Feat: 재생기능 shallow 사용으로 불필요한 리렌더링 막기
  src/components/bill/BillButtonListSection.tsx
  src/components/musicPlayer/MusicPlayerBar.tsx
  src/components/musicPlayer/MusicPlayerFullScreen.tsx
  src/components/musicPlayer/MusicPlayerProgressBar.tsx
  src/constants/billText.ts
  src/hooks/usePlayerControls.ts
  src/pages/Page-GuestBill.tsx
  src/zustand/playNowStore.ts
Labels: 수정

#24 Feat: 스포티파이 트랙 영수증 구현 #21
  src/api/supabase/profilesTableAccessApis.ts
  src/components/bill/BillBox.tsx
  src/components/bill/BillBox_User.tsx
  src/components/bill/BillButtonListSection.tsx
  src/components/common/PlaylistItem.tsx
  src/components/home/Banner.tsx
  src/components/home/BannerItem.tsx
  src/components/mymusic/MusicListItem.tsx
  src/components/mymusic/MusicShelf.tsx
  src/components/mymusic/MusicShelfItem.tsx
  src/components/profile/ProfileLikeBillList.tsx
  src/components/profile/ProfileSmallBill.tsx
  src/constants/billText.ts
  src/constants/bottomSheetText.ts
  src/constants/routes.ts
  src/constants/spinnerText.ts
  src/hooks/usePlayerControls.ts
  src/pages/Page-GuestBill.tsx
  src/pages/Page-MusicShelfDetail.tsx
  src/pages/Page-MyMusicShelfDetail.tsx
  src/pages/Page-SpotifyBill.tsx
  src/pages/PrivateRoute.tsx
Labels: 기능 추가, 스타일
